"use client";

import { useState } from "react";
import { ArrowUpRight, Check, Code2, Mail, Menu, X } from "lucide-react";

const courses = [
  { name: "Scratch", level: "Foundations", desc: "Build your first interactive projects while learning variables, motion, operators, and computational thinking." },
  { name: "Python I", level: "Beginner", desc: "Learn the building blocks of programming: variables, conditionals, loops, functions, and more." },
  { name: "Java I", level: "Beginner", desc: "A gentle introduction to Java, covering core concepts with hands-on practice, homework, and tests." },
  { name: "Python III", level: "Advanced", desc: "Explore object-oriented programming, classes, inheritance, recursion, and advanced data structures." },
  { name: "SAT Math Prep", level: "STEM Program", desc: "Develop the strategies and confidence to succeed on the math portion of the SAT." },
];
const testimonials = [
  ["William", "Winter Session 2022", "The instructors are super knowledgeable and friendly! We will definitely come back for the summer camp!"],
  ["Grace", "Winter Session 2022", "AICS classes are very organized and practical. Thank you for helping the next generation!"],
  ["Vani", "Winter Session 2022", "A great experience for anyone interested in computer science. The instructors are very nice, and the classes are fun!"],
  ["Albert", "Summer Session 2020", "The teachers explain everything thoroughly while allowing students to demonstrate and exercise their knowledge."],
];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [status, setStatus] = useState("");
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; const data = Object.fromEntries(new FormData(form)); const res = await fetch("/api/inquiry", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); setStatus(res.ok ? "Thanks — we’ll be in touch." : "Something went wrong. Please email us directly."); if (res.ok) form.reset(); }
  return <main>
    <nav className="nav"><a href="#top" className="brand"><span className="brand-mark">&lt;/&gt;</span> AICS</a><div className={menuOpen ? "nav-links open" : "nav-links"}><a href="#about" onClick={() => setMenuOpen(false)}>About</a><a href="#courses" onClick={() => setMenuOpen(false)}>Courses</a><a href="#impact" onClick={() => setMenuOpen(false)}>Impact</a><a href="#team" onClick={() => setMenuOpen(false)}>Team</a><a href="#join" className="nav-cta" onClick={() => setMenuOpen(false)}>Join us <ArrowUpRight size={16}/></a></div><button className="menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X/> : <Menu/>}</button></nav>
    <section className="hero" id="top"><div className="grid-glow"/><div className="hero-copy"><p className="eyebrow"><span className="pulse"/> SUMMER 2026 / ENROLLMENT OPEN</p><h1>Learn to <em>think</em><br/> like a <span>builder.</span></h1><p className="hero-sub">Free, live computer science classes for students everywhere. Explore the ideas shaping our future — and build something that matters.</p><div className="hero-actions"><a href="#signup" className="button primary">Apply for Summer 2026 <ArrowUpRight size={18}/></a><a href="#about" className="text-link">Discover AICS <span>↓</span></a></div></div><div className="code-card"><div className="code-top"><span><i/><i/><i/></span><small>hello_world.py</small><Code2 size={15}/></div><pre><code><span className="pink">def</span> <span className="blue">change_the_world</span>():{`\n`}  <span className="pink">for</span> idea <span className="pink">in</span> <span className="blue">curiosity</span>:{`\n`}    <span className="pink">if</span> idea.<span className="blue">is_bold</span>():{`\n`}      <span className="pink">return</span> <span className="green">"build it"</span>{`\n`}  <span className="pink">return</span> <span className="green">"keep learning"</span></code></pre><div className="code-status"><span><Check size={12}/> executed in 0.04s</span><span>Python 3.12</span></div></div><div className="hero-scroll">SCROLL TO EXPLORE <span>↓</span></div></section>
    <section className="stats" id="impact"><div><strong>2,000<span>+</span></strong><p>students taught</p></div><div><strong>34</strong><p>states reached</p></div><div><strong>13</strong><p>countries connected</p></div><div className="sponsor"><p>SUPPORTED BY</p><div><b>Wolfram</b><b>AOPS</b><b>replit</b></div></div></section>
    <section className="about section" id="about"><div className="section-label">01 / THE WHY</div><div><h2>Opportunity should<br/><span>compile for everyone.</span></h2><p className="lead">AICS is a 501(c)(3) nonprofit organization committed to providing an affordable computer science education to students around the world. Through our free classes and philanthropy, we aim to address the significant inequity present in the tech industry and prepare all students for an increasingly tech-driven future.</p><a className="text-link" href="#team">Meet the team <ArrowUpRight size={16}/></a></div></section>
    <section className="team-banner" id="team"><div className="team-art"><div className="orb orb-one"/><div className="orb orb-two"/><div className="team-grid"/></div><div><p className="eyebrow">THE PEOPLE BEHIND THE PROGRAM</p><h2>Small team.<br/><em>Big signal.</em></h2><p>Students teaching students. Engineers, educators, and dreamers building a more equitable future for technology.</p><a href="#join" className="button outline">Meet our team <ArrowUpRight size={17}/></a></div></section>
    <section className="courses section" id="courses"><div className="section-head"><div><div className="section-label">02 / THE WORK</div><h2>Find your <span>language.</span></h2></div><p>Our courses meet Monday through Thursday, July 13–23, 2026. Every class is live, collaborative, and free.</p></div><div className="course-grid">{courses.map((c, i) => <article className="course" key={c.name}><div className="course-num">0{i+1}</div><div><p className="course-level">{c.level}</p><h3>{c.name}</h3><p>{c.desc}</p></div><ArrowUpRight className="course-arrow"/></article>)}</div></section>
    <section className="donate section"><div className="donate-copy"><div className="section-label">03 / THE MISSION IN ACTION</div><h2>Give access.<br/><span>Multiply impact.</span></h2><p>Our present campaign is the AICS Tech Access Initiative, where we seek to help provide education programs around the world with the technological equipment they require to bolster their students&apos; education.</p><p>We have currently raised <b>$3,260</b> of a <b>$15,000</b> goal.</p><div className="progress"><span/></div><div className="progress-label"><span>$3,260 raised</span><span>$15,000 goal</span></div><p className="small">In addition, we have raised close to $10,000 in charitable donations for organizations including Doctors Without Borders, Cambridge Health Alliance, Boston Racial Equity Fund, and Beth Israel Deaconess Medical Center.</p></div><div className="donorbox"><div className="donorbox-mark">DB</div><h3>Support the initiative</h3><p>Your gift equips the next generation of builders.</p><a href="https://donorbox.org" target="_blank" rel="noreferrer" className="button primary">Donate via Donorbox <ArrowUpRight size={17}/></a><small>Secure donation processing</small></div></section>
    <section className="testimonials section"><div className="section-label">04 / IN THEIR WORDS</div><h2>Proof is in the <span>process.</span></h2><div className="quote-grid">{testimonials.map(([name, session, quote]) => <blockquote key={name}><div className="quote-mark">“</div><p>{quote}</p><footer><strong>{name}</strong><span>{session}</span></footer></blockquote>)}</div></section>
    <section className="join" id="join"><div><p className="eyebrow">OPEN CALL / 2026</p><h2>Interested in joining<br/><em>our team?</em></h2><p>Help us make computer science education more accessible. We&apos;re always looking for thoughtful teachers, builders, and believers.</p></div><form onSubmit={submit}><label>Name<input required name="name" placeholder="Your name"/></label><label>Email<input required type="email" name="email" placeholder="you@example.com"/></label><label>Message<textarea required name="message" placeholder="Tell us a little about yourself" rows={3}/></label><button className="button primary" type="submit">Send inquiry <ArrowUpRight size={17}/></button>{status && <p className="form-status">{status}</p>}</form></section>
    <footer className="footer"><div className="brand"><span className="brand-mark">&lt;/&gt;</span> AICS</div><p>A 501(c)(3) nonprofit organization.<br/>Making the future more equitable, one line at a time.</p><div className="footer-links"><a href="mailto:info@actoninstituteofcs.org"><Mail size={16}/> Email us</a><a href="https://instagram.com" target="_blank" rel="noreferrer"><span aria-hidden="true">◎</span> Instagram</a><a href="#top">Back to top ↑</a></div><small>© 2026 Acton Institute of Computer Science</small></footer>
  </main>
}
